type: object
title: Product Collection
properties:
  external_collection_id:
    description: Product collection id on the store website (shopify or woocommerce product id)
    type: string
    examples:
      - "123"
  external_product_ids:
    description: List of external product ids in the collection
    type: array
    items:
      type: string
    examples:
      - ["1234"]
  title:
    description: Title of the product collection
    type: string
    examples:
      - Shoes
  description:
    description: Description of the product collection
    type: string
    examples:
      - A great collection of shoes
  handle:
    description: Unique identifier in the url of the product page. if product page is /collections/shoes, handle would be shoes
    type: string
    examples:
      - shoes
  collection_type:
    description: Custom or Smart
    type: string
    enum: ["custom", "smart"]
    examples:
      - custom
  image_url:
    description: Image for the collection
    type: string
    examples:
      - https://somecdn.com/image/image1.jpg
  updated_at:
    description: The date and time (ISO 8601 format) when the product was updated.
    type: string
    examples:
      - "2022-06-27T08:48:27-04:00"
  published_at:
    description: The date and time (ISO 8601 format) when the product was created.
    type: string
    examples:
      - "2022-06-27T08:48:27-04:00"
  

required:
  - external_collection_id
  - title
  - updated_at

